apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: avermaas/kub-demo-auth:1
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 264Mi
              cpu: "0.2"