apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: avermaas/kub-demo-users:2
        env:
          - name: AUTH_ADDRESS
            value: localhost:80
      - name: auth
        image: avermaas/kub-demo-auth:1