apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: avermaas/kub-demo-users:4
        env:
          - name: AUTH_ADDRESS
            value: auth-service.default:80 # service name . namespace : port
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 264Mi
            cpu: "0.2"